[settings]
# Short name (used by CrossCC, should match <name>.ini)
name = aarch64
# Target triple / long identifier used in settings below
id = aarch64-linux-musl
# Free-form description (displayed by CrossCC 'info')
description = Linux ARM 64-bit (Little Endian)

[sysroot]
# URL base of sysroot archive
url = https://musl.cc/aarch64-linux-musl-cross.tgz
# Tool for unpacking the sysroot archive (1: archive filename)
unpack = tar xzf {ARG:1} -C {sysroot.base}
# Installed top directory of sysroot
dir = {sysroot.base}/{settings.id}-cross/{settings.id}
# SHA-256 checksum to verify downloaded archive before unpacking
checksum = 
# Provisioning script (executed after downloading / unpacking)
setup = 
# Environment variables set for all tool invocations
env = 
# Overriding global link setting
link = static

# Basic compiler settings
[compiler]
# Flags used for all builds
flags = -Wall -Wextra --target={settings.id} --sysroot={sysroot.dir} -B{sysroot.dir}/../lib/gcc/{settings.id}/{LATEST} -L{sysroot.dir}/../lib/gcc/{settings.id}/{LATEST}
# Flags appended to end of invocation for all builds
post_flags = 
# Environment variables for compiler invocations
env = 
# -Wx,build=release
release = -O2 -DNDEBUG
# -Wx,build=debug
debug = -O0 -g
# -Wx,sanitize
sanitize = -fsanitize=address,undefined
# -Wx,profile
profile = -pg
# -Wx,optimize=size
size = -Os
# -Wx,optimize=speed
speed = -O3
# -Wx,link=static
static = -static
# -Wx,link=shared
shared = -fPIC

# C specific compiler settings
[compiler-c]
# Semicolon-separated candidate list of C compilers (resolved via PATH)
binary = {settings.id}-gcc;clang;gcc
# Environment variables for C compiler invocations
env = 

# C++ specific compiler settings
[compiler-cxx]
# Semicolon-separated candidate list of C++ compilers (resolved via PATH)
binary = {settings.id}-g++;clang++;g++
# Environment variables for C++ compiler invocations
env = 

# Standalone assembler settings (only for -Wx,mode=assembler)
[assembler]
binary = {settings.id}-as;as
flags = -march=armv8-a
debug = -g

# Standalone linker settings (only for -Wx,mode=linker)
[linker]
binary = {settings.id}-ld;ld
flags = --sysroot={sysroot.dir} -L{sysroot.dir}/lib
release = -s --gc-sections
debug = --export-dynamic

# Archiver for static library creation
[archiver]
binary = {settings.id}-ar;ar
flags = rcs

# Target binary runner
# (for -Wx,mode=runner, and when runner = true set for any of the above modes)
[runner]
binary = qemu-aarch64
# Used for all invocations
flags = -cpu max
# for -Wx,mode=debugger
debug = -g 1234

# Debugger (for -Wx,mode=debugger)
[debugger]
binary = gdb-multiarch;gdb
flags = -ex "target remote :1234"
