# Global configuration

[env]
XDG_CACHE_HOME = {ENV:HOME}/.cache
XDG_DATA_HOME = {ENV:HOME}/.local/share

[settings]
# Paths where downloaded archives are cached (semicolon-separated)
cache = {ENV:XDG_CACHE_HOME}/crosscc
# Tool for downloading archives (1: URL, 2: destination)
download = curl -sSL {ARG:1} -o {ARG:2}
# Search path for .ini files (semicolon-separated)
inifiles = {ENV:XDG_DATA_HOME}/crosscc/ini

[modes]
# Mapping binary names ('cr<name>') to 'mode=...' settings
cc = compiler-c
cxx = compiler-cxx
as = assembler
ld = linker
ar = archiver
run = runner
db = debugger

[supermodes]
# Mapping specialized modes to their shared settings
compiler-c = compiler
compiler-cxx = compiler

[sysroot]
# Base directory for sysroots
base = {ENV:XDG_DATA_HOME}/crosscc/sysroots
# Global link preference (static / shared)
link = static
